services:
  - type: web
    name: render-proxy
    runtime: node
    region: ohio
    plan: free
    buildCommand: echo "no build needed"
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: BROWSERLESS_SELF_URL
        value: https://browserless-v3.onrender.com
      - key: BROWSERLESS_API_URL
        sync: false
      - key: BROWSERLESS_API_TOKEN
        sync: false

  - type: web
    name: browserless-v3
    runtime: docker
    region: ohio
    plan: free
    dockerfilePath: ./browserless/docker/chromium/Dockerfile
    dockerContext: ./browserless
    healthCheckPath: /pressure
    envVars:
      - key: CONCURRENT
        value: "5"
      - key: QUEUED
        value: "10"
      - key: TIMEOUT
        value: "30000"
